import Head from 'next/head'
import Image from 'next/image'
import React, {useState, useRef} from 'react'
import { useOnClickOutside } from '../hooks'
import styles from '../styles/Home.module.css'

import Burger from '../components/Burger'
import Menu from '../components/Menu'

export default function TestEmotion() {

  const [open, setOpen] = useState(false);
  const node = useRef();
  
  useOnClickOutside(node, () => setOpen(false));

    return (
      <div className={styles.container}>
      <Head>
        <title>Swol Not Swollen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        
        <div>Test Emotion page</div>

        <div ref={node}>
          <Burger open={open} setOpen={setOpen}/>
          <Menu open={open} setOpen={setOpen}/>
        </div>
      </div>
    )
}